INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',1,'القيمة المنزلية','ما القيمة المنزلية للرقم 7 في العدد 572؟','["7", "70", "700", "500"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',1,'القيمة المنزلية','ما القيمة المنزلية للرقم 5 في العدد 5,214؟','["5", "50", "500", "5000"]',3);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',1,'القيمة المنزلية','أي عدد يساوي 600 + 30 + 4؟','["634", "643", "364", "604"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',1,'القيمة المنزلية','أي عدد أكبر؟ 4,305 أم 4,350؟','["4,305", "4,350", "متساويان", "لا يمكن"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',1,'القيمة المنزلية','ما العدد الذي يأتي بعد 999؟','["998", "1000", "1001", "990"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',2,'القيمة المنزلية','ما القيمة المنزلية للرقم 8 في 8,245؟','["8", "80", "800", "8000"]',3);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',2,'القيمة المنزلية','أي عدد يقع بين 4,000 و5,000؟','["3,999", "4,250", "5,100", "6,000"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',2,'القيمة المنزلية','اكتب 7,042 بالصورة التحليلية.','["7,000+40+2", "700+40+2", "7,000+400+2", "7,000+4+2"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',2,'القيمة المنزلية','أي الأعداد أقرب إلى 3,000؟','["2,950", "2,100", "3,800", "4,000"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',2,'القيمة المنزلية','رتب 2,305 و2,350 و2,053 تصاعديًا.','["2,053،2,305،2,350", "2,305،2,053،2,350", "2,350،2,305،2,053", "2,053،2,350،2,305"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',3,'التقدير','قدّر 398 + 201 إلى أقرب مئة.','["500", "600", "700", "800"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',3,'التقدير','قدّر 612 - 287 إلى أقرب مئة.','["200", "300", "400", "500"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',3,'التقدير','أي تقدير مناسب لـ 491 + 310؟','["500", "600", "800", "1000"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',3,'التقدير','قرّب 749 إلى أقرب مئة.','["700", "750", "800", "900"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',3,'التقدير','قرّب 3,249 إلى أقرب ألف.','["2,000", "3,000", "3,500", "4,000"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',4,'الجمع','ما ناتج 245 + 137؟','["372", "382", "392", "402"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',4,'الجمع','ما ناتج 326 + 214؟','["530", "540", "550", "560"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',4,'الجمع','ما ناتج 125 + 375؟','["400", "450", "500", "550"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',4,'الجمع','مع أحمد 235 ريالًا وأعطاه والده 120 ريالًا، كم أصبح معه؟','["345", "355", "365", "375"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',4,'الجمع','ما العدد المفقود: 240 + □ = 500؟','["240", "250", "260", "270"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',5,'الطرح','ما ناتج 600 - 245؟','["345", "355", "365", "375"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',5,'الطرح','ما ناتج 732 - 300؟','["332", "432", "532", "632"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',5,'الطرح','مع سارة 500 ريال، أنفقت 175 ريالًا. كم بقي؟','["315", "325", "335", "345"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',5,'الطرح','ما العدد المفقود: 700 - □ = 450؟','["150", "200", "250", "300"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',5,'الطرح','ما ناتج 900 - 425؟','["465", "475", "485", "495"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',7,'خصائص الجمع وقواعد الطرح','أي خاصية تمثل 8 + 5 = 5 + 8؟','["التجميع", "التبديل", "التوزيع", "المحايد"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',7,'خصائص الجمع وقواعد الطرح','أي عدد إذا أضيف إلى 12 لا يغير الناتج؟','["0", "1", "12", "-12"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',7,'خصائص الجمع وقواعد الطرح','أي عبارة صحيحة؟','["7+0=0", "7+0=7", "7+1=1", "7-0=0"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',7,'خصائص الجمع وقواعد الطرح','ما ناتج 9 + 6 + 4 إذا جمعنا 6 + 4 أولًا؟','["17", "18", "19", "20"]',3);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',7,'خصائص الجمع وقواعد الطرح','أي عملية تساعد على التحقق من الطرح؟','["الجمع", "الضرب", "القسمة", "التقريب فقط"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',8,'تمثيل البيانات','إذا كان عدد الكتب المقروءة: علي 3، سارة 5، خالد 2، فمن قرأ أكثر؟','["علي", "سارة", "خالد", "متساوون"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',8,'تمثيل البيانات','ما التمثيل المناسب لمقارنة أعداد مجموعات؟','["رسم بالأعمدة", "ساعة", "مسطرة", "خريطة"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',8,'تمثيل البيانات','إذا كانت القيم 2،4،4،1 فما القيمة الأكثر تكرارًا؟','["1", "2", "4", "6"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',8,'تمثيل البيانات','في جدول: الأحد 4 طلاب، الاثنين 6، أي يوم أكثر؟','["الأحد", "الاثنين", "متساويان", "لا يمكن"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',8,'تمثيل البيانات','ما فائدة الجدول؟','["تنظيم البيانات", "إخفاء البيانات", "زيادة الأعداد", "حذف المعلومات"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',10,'الجمل العددية والدوال','إذا كان 9 + □ = 14، فما العدد؟','["3", "4", "5", "6"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',10,'الجمل العددية والدوال','إذا كانت قاعدة الدالة +2، فما ناتج 5؟','["6", "7", "8", "9"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',10,'الجمل العددية والدوال','أي جملة عددية صحيحة؟','["8+2=9", "8+2=10", "8+2=11", "8+2=12"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',10,'الجمل العددية والدوال','إذا كان المدخل 4 والقاعدة ×3، فما المخرج؟','["7", "8", "12", "16"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',10,'الجمل العددية والدوال','ما العدد الذي يجعل 20 - □ = 13؟','["5", "6", "7", "8"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',13,'الجمع والطرح','ما ناتج 148 + 252؟','["390", "400", "410", "420"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',13,'الجمع والطرح','ما ناتج 521 - 198؟','["313", "323", "333", "343"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',13,'الجمع والطرح','في مكتبة 320 كتابًا، أضيف 85 كتابًا. كم أصبح؟','["395", "405", "415", "425"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',13,'الجمع والطرح','كان في الحافلة 450 راكبًا عبر عدة رحلات، خرج 125. كم بقي؟','["315", "325", "335", "345"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',13,'الجمع والطرح','ما ناتج 675 + 125؟','["700", "750", "800", "850"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',16,'مراجعة','أي عدد أكبر؟ 5,670 أم 5,607؟','["5,670", "5,607", "متساويان", "لا يمكن"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',16,'مراجعة','ما ناتج 300 + 450؟','["650", "700", "750", "800"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',16,'مراجعة','ما ناتج 800 - 275؟','["515", "525", "535", "545"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',16,'مراجعة','قرّب 451 إلى أقرب مئة.','["400", "450", "500", "550"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',16,'مراجعة','إذا كان 6 + س = 15، فما س؟','["7", "8", "9", "10"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',1,'تطبيق ومراجعة','كم يساوي 3 مئات و4 عشرات و6 آحاد؟','["346", "364", "436", "304"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',2,'تطبيق ومراجعة','ما العدد الذي يمثل 9 آلاف و2 مئات؟','["9,020", "9,200", "9,002", "9,220"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',3,'تطبيق ومراجعة','أي عدد يقع قبل 5,000 مباشرة؟','["4,999", "5,001", "4,990", "5,010"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',4,'تطبيق ومراجعة','ما ناتج 420+80؟','["480", "490", "500", "510"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',5,'تطبيق ومراجعة','ما ناتج 950-50؟','["850", "900", "950", "1000"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',6,'تطبيق ومراجعة','معلم لديه 245 ورقة وأعطاه زميله 155. كم ورقة؟','["390", "400", "410", "420"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',7,'تطبيق ومراجعة','في صندوق 700 قلمًا أُخرج 260. كم بقي؟','["430", "440", "450", "460"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',8,'تطبيق ومراجعة','أي عبارة تمثل خاصية التبديل؟','["3+4=4+3", "3+4=3+3", "3+4=7+1", "3+4=0"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',9,'تطبيق ومراجعة','إذا كان المدخل 6 والقاعدة +4 فالمخرج؟','["8", "9", "10", "11"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',10,'تطبيق ومراجعة','إذا كان المدخل 3 والقاعدة ×4 فالمخرج؟','["7", "10", "12", "14"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',11,'تطبيق ومراجعة','في استبيان اختار 7 طلاب الخيار أ و4 الخيار ب. أيهما أكثر؟','["أ", "ب", "متساويان", "لا نعرف"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',12,'تطبيق ومراجعة','ما عدد البيانات في المجموعة 3،5،2،8؟','["3", "4", "5", "8"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',13,'تطبيق ومراجعة','ما أكبر قيمة في 2،9،6،4؟','["2", "4", "6", "9"]',3);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',14,'تطبيق ومراجعة','ما أصغر قيمة في 7،1،5،3؟','["1", "3", "5", "7"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',15,'تطبيق ومراجعة','ما ناتج 234+166؟','["390", "400", "410", "420"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',16,'تطبيق ومراجعة','ما ناتج 500-126؟','["364", "374", "384", "394"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',17,'تطبيق ومراجعة','ما ناتج 125+125؟','["200", "225", "250", "275"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',1,'تطبيق ومراجعة','ما ناتج 640-240؟','["300", "400", "500", "600"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',2,'تطبيق ومراجعة','إذا كان مع خالد 275 وأصبح معه 400، كم أضيف له؟','["115", "125", "135", "145"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',3,'تطبيق ومراجعة','إذا كان العدد 3,485، فما رقم الآحاد؟','["3", "4", "8", "5"]',3);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',4,'تطبيق ومراجعة','إذا كان العدد 6,712، فما رقم المئات؟','["6", "7", "1", "2"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',5,'تطبيق ومراجعة','أي عدد أقرب إلى 700؟','["649", "701", "760", "820"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',6,'تطبيق ومراجعة','قدّر 249+251 إلى أقرب مئة.','["400", "500", "600", "700"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',7,'تطبيق ومراجعة','قدّر 801-298 إلى أقرب مئة.','["400", "500", "600", "700"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',8,'تطبيق ومراجعة','ما العدد المفقود 350+□=600؟','["150", "200", "250", "300"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',9,'تطبيق ومراجعة','ما العدد المفقود 900-□=650؟','["150", "200", "250", "300"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',10,'تطبيق ومراجعة','أي جملة صحيحة؟','["15-5=5", "15-5=10", "15-5=15", "15-5=20"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',11,'تطبيق ومراجعة','إذا كانت قاعدة الدالة -2 والمدخل 9 فالمخرج؟','["5", "6", "7", "8"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',12,'تطبيق ومراجعة','أي تمثيل يساعد على رؤية الفرق بين مجموعتين؟','["رسم بالأعمدة", "النص فقط", "الساعة", "المسطرة"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'رياضيات',13,'تطبيق ومراجعة','إذا كان عدد الحضور السبت 8 والأحد 10، كم يزيد الأحد؟','["1", "2", "3", "4"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',1,'المفردات','ما ضد كلمة «بداية»؟','["نهاية", "خطوة", "طريق", "لقاء"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',1,'المفردات','ما مرادف «سعيد»؟','["حزين", "فرح", "غاضب", "متعب"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',1,'المفردات','أي كلمة تدل على مكان؟','["مدرسة", "يكتب", "جميل", "سريع"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',1,'المفردات','أي كلمة جمع؟','["كتاب", "كتابان", "كتب", "كاتب"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',1,'المفردات','أي كلمة مؤنثة؟','["معلم", "معلمة", "طالب", "كاتب"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',2,'الفهم القرائي','ما السؤال الذي يساعد على معرفة الفكرة الرئيسة؟','["ما الموضوع؟", "كم كلمة؟", "ما لون الورق؟", "ما رقم الصفحة؟"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',2,'الفهم القرائي','إذا ذكر النص فوائد القراءة، فالفكرة الرئيسة تدور حول ماذا؟','["فوائد القراءة", "لون الكتاب", "عدد الصفحات", "اسم القارئ"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',2,'الفهم القرائي','ما الذي نفعله لمعرفة تسلسل الأحداث؟','["نرتبها حسب ورودها", "نحذفها", "نغيرها", "نكررها"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',2,'الفهم القرائي','إذا كانت النتيجة «ابتلت الأرض»، فما السبب المحتمل؟','["هطول المطر", "طلوع الشمس", "القراءة", "النوم"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',2,'الفهم القرائي','ما الغرض من عنوان النص؟','["إعطاء فكرة عن الموضوع", "زيادة طول النص", "إخفاء الموضوع", "تغيير الأحداث"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',5,'التلخيص','ما الهدف الأساسي من التلخيص؟','["ذكر الأفكار الرئيسة باختصار", "إطالة النص", "نسخ النص", "حذف الفكرة الرئيسة"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',5,'التلخيص','في التلخيص نبتعد عن؟','["التفاصيل غير المهمة", "الأفكار الرئيسة", "الفكرة العامة", "المعنى"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',5,'التلخيص','أفضل تلخيص يحافظ على؟','["المعنى الرئيس", "كل الكلمات", "كل الأمثلة", "التكرار"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',5,'التلخيص','قبل التلخيص من الأفضل أن؟','["نحدد الأفكار الرئيسة", "نحذف العنوان", "نغير الموضوع", "ننسخ النص"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',5,'التلخيص','التلخيص الجيد يكون؟','["مختصرًا وواضحًا", "طويلًا جدًا", "بلا معنى", "مكررًا"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',7,'أخلاق المسلم','شخص يفي بوعده؛ ما الخلق؟','["الأمانة", "الكسل", "العجلة", "التردد"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',7,'أخلاق المسلم','من صور التعاون؟','["مساعدة الآخرين", "إهمالهم", "إيذاؤهم", "رفض العمل"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',7,'أخلاق المسلم','ما السلوك الذي يدل على الصدق؟','["قول الحقيقة", "الكذب", "إخفاء الحقائق", "الغش"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',7,'أخلاق المسلم','كيف نحافظ على الأمانة؟','["نؤدي ما اؤتمنّا عليه", "نهملها", "نخفيها", "نضيعها"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (3,'لغتي',7,'أخلاق المسلم','ما نتيجة التعاون؟','["إنجاز العمل بصورة أفضل", "تعطيل العمل", "زيادة الخلاف", "ترك العمل"]',0);
