INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',14,'القياس','كم سنتيمترًا في 2 متر؟','["20", "100", "200", "2000"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',14,'القياس','كم مليمترًا في 1 سنتيمتر؟','["1", "5", "10", "100"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',14,'القياس','أي وحدة أنسب لقياس سعة زجاجة؟','["لتر", "كيلوغرام", "متر", "سنتيمتر"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',14,'القياس','أي وحدة أنسب لقياس كتلة حقيبة؟','["كيلوغرام", "لتر", "متر", "سم"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',14,'القياس','3 أمتار تساوي؟','["30 سم", "300 سم", "3000 سم", "3 سم"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',1,'تطبيق ومراجعة','ما الحد التالي 10،20،30،40؟','["45", "50", "55", "60"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',2,'تطبيق ومراجعة','إذا كانت القاعدة -3 والمدخل 10 فالمخرج؟','["5", "6", "7", "8"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',3,'تطبيق ومراجعة','إذا س=9 فما س-4؟','["4", "5", "6", "7"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',4,'تطبيق ومراجعة','ما قيمة 4²؟','["8", "12", "16", "20"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',5,'تطبيق ومراجعة','أي عدد من مضاعفات 5؟','["12", "13", "15", "17"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',6,'تطبيق ومراجعة','ما العامل المشترك بين 8 و12؟','["2", "3", "5", "7"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',7,'تطبيق ومراجعة','أي عدد أولي؟','["9", "11", "15", "21"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',8,'تطبيق ومراجعة','ما قيمة 10²؟','["20", "50", "100", "1000"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',9,'تطبيق ومراجعة','إذا كان المدخل 7 والقاعدة ×3 فالمخرج؟','["10", "14", "21", "24"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',10,'تطبيق ومراجعة','أي عبارة تعني «س ناقص 8»؟','["س+8", "س-8", "8-س", "8س"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',11,'تطبيق ومراجعة','إذا ص=6 فما ص÷2؟','["2", "3", "4", "5"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',12,'تطبيق ومراجعة','أي تمثيل يناسب متابعة درجة الحرارة خلال أسبوع؟','["الخطوط", "الأعمدة فقط", "النص", "الصور"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',13,'تطبيق ومراجعة','إذا كانت القيم 3،5،7،9 فما الفرق بين أكبر وأصغر قيمة؟','["4", "5", "6", "7"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',14,'تطبيق ومراجعة','ما ناتج 4.2×10؟','["0.42", "4.2", "42", "420"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',15,'تطبيق ومراجعة','ما ناتج 0.7×10؟','["0.07", "0.7", "7", "70"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',16,'تطبيق ومراجعة','ما ناتج 12.6÷3؟','["3.2", "4.2", "5.2", "6.2"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',17,'تطبيق ومراجعة','ما ناتج 5.6÷7؟','["0.6", "0.7", "0.8", "0.9"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',1,'تطبيق ومراجعة','أي عدد عشري أكبر؟','["0.4", "0.35", "0.39", "0.405"]',3);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',2,'تطبيق ومراجعة','رتب 0.2،0.5،0.3 تصاعديًا.','["0.2،0.3،0.5", "0.5،0.3،0.2", "0.3،0.2،0.5", "0.2،0.5،0.3"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',3,'تطبيق ومراجعة','أي كسر يساوي 3/6؟','["1/2", "1/3", "2/3", "3/4"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',4,'تطبيق ومراجعة','أي كسر أكبر؟','["2/3", "1/3", "1/4", "1/5"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',5,'تطبيق ومراجعة','حوّل 9/4 إلى عدد كسري.','["1 1/4", "2 1/4", "2 2/4", "3 1/4"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',6,'تطبيق ومراجعة','ما الكسر الذي يمثل 0.25؟','["1/2", "1/4", "2/5", "3/4"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',7,'تطبيق ومراجعة','2/8 + 3/8 = ؟','["4/8", "5/8", "6/8", "7/8"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',8,'تطبيق ومراجعة','7/10 - 2/10 = ؟','["3/10", "4/10", "5/10", "6/10"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',9,'تطبيق ومراجعة','1/4 من 20 = ؟','["4", "5", "6", "8"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',10,'تطبيق ومراجعة','1/5 من 30 = ؟','["5", "6", "7", "8"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',11,'تطبيق ومراجعة','4 كيلومترات تساوي كم مترًا؟','["40", "400", "4000", "40000"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',12,'تطبيق ومراجعة','2500 متر تساوي؟','["2.5 كم", "25 كم", "250 كم", "0.25 كم"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',13,'تطبيق ومراجعة','5000 مل تساوي؟','["0.5 لتر", "5 لترات", "50 لترًا", "500 لتر"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',14,'تطبيق ومراجعة','2 كجم تساوي؟','["20 جم", "200 جم", "2000 جم", "20000 جم"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',1,'الأنماط والدوال','أي خيار مما يلي يعبّر بصورة صحيحة عن: إذا كان النمط 4،8،12،16 فما التالي؟','["18", "20", "22", "24"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',1,'الأنماط والدوال','في موقف مشابه للدرس، ما الإجابة الصحيحة؟ ما قاعدة النمط 3،6،9،12؟','["+2", "+3", "+4", "×3"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',1,'الأنماط والدوال','اختر الإجابة الأدق: إذا كان المدخل 5 والقاعدة +7 فالمخرج؟','["10", "11", "12", "13"]',3);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'رياضيات',1,'الأنماط والدوال','أي خيار مما يلي يعبّر بصورة صحيحة عن: إذا كانت القاعدة ×2 والمدخل 8 فالمخرج؟','["10", "12", "14", "16"]',3);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',1,'المفردات','ما مرادف «القدوة»؟','["النموذج المحتذى", "المكان", "الطريق", "الكتاب"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',1,'المفردات','ما ضد «الشجاعة»؟','["الجبن", "القوة", "الكرم", "الصدق"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',1,'المفردات','أي كلمة مناسبة في سياق يدل على النجاح؟','["إنجاز", "فشل", "إهمال", "تأخر"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',1,'المفردات','ما معنى «يقتدي»؟','["يتبع مثالًا صالحًا", "يبتعد", "ينسى", "يعارض"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',1,'المفردات','أي زوج من الكلمات متقارب المعنى؟','["شجاع/جريء", "سريع/بطيء", "حاضر/غائب", "كبير/صغير"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',2,'الفهم القرائي','كيف نحدد الفكرة الرئيسة للنص؟','["نبحث عن الفكرة الأهم التي يدور حولها", "نعد الكلمات", "نقرأ العنوان فقط", "نحذف التفاصيل"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',2,'الفهم القرائي','المعلومة المذكورة صراحة في النص تسمى؟','["مباشرة", "مخفية", "خيالية", "غير مرتبطة"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',2,'الفهم القرائي','ما الذي يساعد على الاستنتاج؟','["ربط الأدلة", "تجاهل النص", "التخمين بلا دليل", "حذف الفقرات"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',2,'الفهم القرائي','ما الغرض من النص الذي يشرح خطوات عمل؟','["التوضيح/التعليم", "التسلية فقط", "الوصف فقط", "الإقناع دائمًا"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',2,'الفهم القرائي','إذا كان النص يحكي أحداثًا وشخصيات فهو غالبًا؟','["سردي", "إجرائي", "جدول", "قائمة"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',5,'الإملاء','أي كلمة تبدأ بهمزة قطع؟','["أحمد", "ابن", "استخرج", "اكتب"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',5,'الإملاء','أي كلمة تبدأ بهمزة وصل؟','["استمع", "أحمد", "إكرام", "أخذ"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',5,'الإملاء','أي كتابة صحيحة؟','["ابن", "إبن", "إبنّ", "ابنَ"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',5,'الإملاء','أي كلمة تحتوي همزة متطرفة؟','["شاطئ", "مدرسة", "كتاب", "قلم"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',5,'الإملاء','أي كلمة كتبت همزتها المتوسطة بصورة صحيحة؟','["سُئل", "سءل", "سؤالٌا", "سئال"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',7,'النحو','في «كان الجو معتدلًا»، ما خبر كان؟','["كان", "الجو", "معتدلًا", "الجملة"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',7,'النحو','ما اسم كان في «كان الطالب مجتهدًا»؟','["كان", "الطالب", "مجتهدًا", "لا يوجد"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',7,'النحو','أي جملة فيها اسم مجرور بحرف الجر؟','["ذهبت إلى المدرسة", "قرأ الطالب الدرس", "الجو جميل", "كتب خالد"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',7,'النحو','ما علامة جر الاسم المفرد؟','["الكسرة", "الضمة", "الفتحة", "السكون"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',7,'النحو','في «مررت بالحديقة»، ما الاسم المجرور؟','["مررت", "الباء", "الحديقة", "الجملة"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',8,'اسم الفاعل واسم المفعول','ما اسم الفاعل من «كتب»؟','["كاتب", "مكتوب", "كتاب", "كتابة"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',8,'اسم الفاعل واسم المفعول','ما اسم المفعول من «كتب»؟','["كاتب", "مكتوب", "كتاب", "كتابة"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',8,'اسم الفاعل واسم المفعول','ما اسم الفاعل من «نصر»؟','["ناصر", "منصور", "نصر", "نصير"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',8,'اسم الفاعل واسم المفعول','ما اسم المفعول من «حفظ»؟','["حافظ", "محفوظ", "حفظ", "حافظة"]',1);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',8,'اسم الفاعل واسم المفعول','أي كلمة اسم فاعل؟','["قارئ", "مقروء", "قراءة", "كتاب"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',11,'وصف الشخصية والتلخيص','عند وصف شخصية نذكر صفاتها مدعومة بـ؟','["سلوكها وأفعالها", "اسمها فقط", "العنوان فقط", "رقم الصفحة"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',11,'وصف الشخصية والتلخيص','التلخيص الجيد يحافظ على؟','["الأفكار الرئيسة", "كل التفاصيل", "التكرار", "الأمثلة كلها"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',11,'وصف الشخصية والتلخيص','قبل التلخيص نحدد؟','["الأفكار الرئيسة", "عدد الحروف", "نوع الخط", "رقم الصفحة"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',11,'وصف الشخصية والتلخيص','أي جملة تلخص فكرة طويلة؟','["جملة موجزة تجمع المعنى الرئيس", "نسخ الفقرة", "تكرار كل التفاصيل", "حذف المعنى"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',11,'وصف الشخصية والتلخيص','ما الذي يجب تجنبه في التلخيص؟','["الإطالة والتكرار", "الوضوح", "الاختصار", "ترتيب الأفكار"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',13,'التواصل الكتابي والشفهي','ما أول ما يساعد على كتابة تلخيص؟','["فهم النص", "نسخه", "حذف العنوان", "تغيير الموضوع"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',13,'التواصل الكتابي والشفهي','العرض الشفهي الجيد يحتاج إلى؟','["ترتيب الأفكار ووضوح الصوت", "السرعة الشديدة", "قراءة بلا فهم", "الصمت"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',13,'التواصل الكتابي والشفهي','عند عرض سيرة شخص نذكر؟','["أهم محطات حياته", "أرقام عشوائية", "تفاصيل لا علاقة لها", "عنوان فقط"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',13,'التواصل الكتابي والشفهي','ما وسيلة مناسبة لدعم العرض؟','["نقاط مرتبة/صور مناسبة", "إخفاء الأفكار", "تكرار كلمة واحدة", "عدم التحضير"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',13,'التواصل الكتابي والشفهي','في التواصل الكتابي نراعي؟','["وضوح الفكرة وصحة اللغة", "الغموض", "التكرار", "الحذف العشوائي"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',1,'تطبيق ومراجعة','ما مرادف «العزم»؟','["الإرادة", "الكسل", "الخوف", "النسيان"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',2,'تطبيق ومراجعة','ما ضد «النجاح»؟','["الفشل", "التقدم", "الإنجاز", "التفوق"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',3,'تطبيق ومراجعة','أي كلمة تدل على الجمع؟','["طلاب", "طالب", "طالبة", "كاتب"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',4,'تطبيق ومراجعة','أي كلمة تدل على المثنى؟','["طالبان", "طلاب", "طالب", "طالبات"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',5,'تطبيق ومراجعة','أي كلمة اسم؟','["مدرسة", "يكتب", "سريع", "اقرأ"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',6,'تطبيق ومراجعة','أي كلمة فعل؟','["نجح", "نجاح", "ناجح", "مدرسة"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',7,'تطبيق ومراجعة','ما السؤال الذي يكشف السبب؟','["لماذا؟", "متى؟", "أين؟", "من؟"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',8,'تطبيق ومراجعة','ما السؤال الذي يكشف المكان؟','["أين؟", "لماذا؟", "متى؟", "كيف؟"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',9,'تطبيق ومراجعة','ما السؤال الذي يكشف الطريقة؟','["كيف؟", "من؟", "أين؟", "متى؟"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',10,'تطبيق ومراجعة','ما الفكرة الرئيسة لنص يتحدث عن أهمية القراءة؟','["أهمية القراءة", "لون الكتاب", "عدد الصفحات", "اسم الطباعة"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',11,'تطبيق ومراجعة','إذا ذكر النص «لذلك» فهي غالبًا تشير إلى؟','["نتيجة أو علاقة سببية", "مكان", "شخص", "زمن فقط"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',12,'تطبيق ومراجعة','ما الفرق بين الفكرة الرئيسة والتفصيل؟','["الرئيسة أعم والتفصيل يدعمها", "هما متطابقان دائمًا", "التفصيل أهم دائمًا", "لا فرق"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',13,'تطبيق ومراجعة','ما المقصود بنوع النص؟','["طبيعته مثل سردي أو معلوماتي", "عدد صفحاته", "حجمه", "لونه"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',14,'تطبيق ومراجعة','أي نص هدفه إعطاء تعليمات؟','["إجرائي", "شعري فقط", "قصصي فقط", "إعلاني دائمًا"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',15,'تطبيق ومراجعة','أي كلمة صحيحة بهمزة قطع؟','["إكرام", "استعمال", "ابن", "اجلس"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',16,'تطبيق ومراجعة','أي كلمة صحيحة بهمزة وصل؟','["استعمال", "أحمد", "إكرام", "أخذ"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',17,'تطبيق ومراجعة','ما الهمزة المتطرفة في كلمة «شاطئ»؟','["ء", "ا", "و", "لا توجد"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',1,'تطبيق ومراجعة','ما اسم الفاعل من «قرأ»؟','["قارئ", "مقروء", "قراءة", "قرآن"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',2,'تطبيق ومراجعة','ما اسم المفعول من «حفظ»؟','["حافظ", "محفوظ", "حفظ", "حفيظ"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',3,'تطبيق ومراجعة','في «كان الطالب نشيطًا» ما خبر كان؟','["الطالب", "كان", "نشيطًا", "لا شيء"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',4,'تطبيق ومراجعة','في «ذهبت إلى المدرسة» ما الاسم المجرور؟','["ذهبت", "إلى", "المدرسة", "الجملة"]',2);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',5,'تطبيق ومراجعة','أي حرف جر؟','["في", "كتب", "طالب", "جميل"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',6,'تطبيق ومراجعة','ما علامة جر الاسم المفرد؟','["الكسرة", "الضمة", "الفتحة", "الألف"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',7,'تطبيق ومراجعة','ما الذي يميز اسم الفاعل؟','["يدل على من قام بالفعل", "يدل على من وقع عليه فقط", "يدل على المكان", "يدل على الزمن"]',0);
INSERT INTO questions(grade,subject,week,lesson,question,choices_json,answer_index) VALUES (6,'لغتي',8,'تطبيق ومراجعة','ما الذي يميز اسم المفعول؟','["يدل على من وقع عليه الفعل", "يدل على الفاعل", "يدل على المكان", "يدل على الزمن"]',0);
