INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',1,'التعامل مع الترحيب والنشاطات التمهيدية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',2,'التعامل مع الترحيب: جارنا الجديد');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',3,'أخلاق المهنة: نشاطات التهيئة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',4,'مراجعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',5,'القراءة والتلخيص: أنشطة التهيئة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',6,'القراءة والتلخيص: مراجعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',7,'أخلاق المسلم: النشاطات');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',8,'أخلاق المسلم: مراجعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',9,'أخلاق المسلم: نصوص وتطبيقات');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',10,'أخلاق المسلم: وصف شخصية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',11,'آفاق واسعة: البئر');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',12,'آفاق واسعة: البئر ومراجعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',13,'وسائل الاتصالات: الهاتف النقال');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',14,'وسائل الاتصالات: الهاتف النقال');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',15,'وسائل الاتصالات: الهاتف النقال');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',16,'وسائل الاتصالات: القراءة والاستماع');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'لغتي',17,'مراجعة عامة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',1,'القيمة المنزلية ضمن 1000');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',2,'القيمة المنزلية ضمن 100000 والملايين');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',3,'مقارنة الأعداد وترتيبها وتقدير الجمع والطرح');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',4,'طرائق الجمع الذهني واستقصاء حل المسألة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',5,'طرائق الجمع والطرح واستقصاء حل المسألة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',6,'الجمع والطرح بالتجميع وإعادة التجميع');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',7,'الجبر: خصائص الجمع وقواعد الطرح');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',8,'تمثيل البيانات وقراءتها');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',9,'الجداول والتمثيلات البيانية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',10,'الجمل العددية وجداول الدوال');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',11,'جداول الجمع والطرح');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',12,'مراجعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',13,'جمع الأعداد المكونة من رقمين أو ثلاثة أرقام');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',14,'طرح الأعداد المكونة من رقمين أو ثلاثة أرقام');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',15,'جمع وطرح الأعداد باستراتيجيات متنوعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',16,'مراجعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (3,'رياضيات',17,'مراجعة عامة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',1,'قدوات ومثل عليا: الوحدة والتهيئة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',2,'قدوات ومثل عليا: نص الفهم القرائي');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',3,'قدوات ومثل عليا: نص الاستماع والتطبيقات');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',4,'قدوات ومثل عليا: استراتيجية القراءة ومراجعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',5,'قدوات ومثل عليا: الظاهرة الإملائية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',6,'قدوات ومثل عليا: الهمزات');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',7,'قدوات ومثل عليا: الوظيفة النحوية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',8,'قدوات ومثل عليا: اسم الفاعل واسم المفعول');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',9,'قدوات ومثل عليا: الرسم الكتابي');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',10,'قدوات ومثل عليا: عمر بن الخطاب ورسول كسرى');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',11,'آفاق واسعة: وصف الشخصية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',12,'آفاق واسعة: التلخيص');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',13,'وسائل الاتصالات: التواصل الكتابي');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',14,'وسائل الاتصالات: التواصل الشفهي');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',15,'وسائل الاتصالات: الشفهي والكتابي');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',16,'مراجعة شاملة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'لغتي',17,'مراجعة عامة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',1,'الجبر: الأنماط العددية والدوال');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',2,'الجبر: الأنماط العددية والدوال');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',3,'المتغيرات والعبارات');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',4,'العوامل الأولية والقوى والأسس');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',5,'التمثيل بالأعمدة وبالخطوط');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',6,'ضرب الكسور العشرية في أعداد كلية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',7,'قسمة الكسور العشرية على أعداد كلية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',8,'العمليات على الكسور العشرية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',9,'الكسور الاعتيادية والكسور العشرية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',10,'الكسور الاعتيادية والكسور العشرية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',11,'العمليات على الكسور الاعتيادية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',12,'الكسور الاعتيادية والكسور العشرية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',13,'الكسور الاعتيادية والكسور العشرية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',14,'الطول والكتلة والسعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',15,'القياس والتحويل بين الوحدات');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',16,'مراجعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'رياضيات',17,'مراجعة عامة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',1,'التنظيم والنظافة العلمية: المهارات العلمية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',2,'الخلية: الخلايا النباتية والخلايا الحيوانية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',3,'الخلية: الخلية النباتية والحيوانية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',4,'الخلية والوظيفة: انقسام الخلايا');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',5,'الخلية والوراثة: الكائنات والصفات');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',6,'الخلية والوراثة: الصفات والأنماط');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',7,'عمليات الحياة في النباتات والمخلوقات الحية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',8,'عمليات الحياة في النباتات والمخلوقات الحية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',9,'عمليات الحياة في الإنسان: التنفس والدوران');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',10,'عمليات الحياة في الإنسان: التغذية والإخراج');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',11,'النظم البيئية: السلاسل والشبكات الغذائية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',12,'النظم البيئية: السلاسل والشبكات الغذائية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',13,'النظم البيئية: مقارنة الأنظمة البيئية');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',14,'موارد الأرض والمحافظة عليها');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',15,'موارد الأرض والمحافظة عليها');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',16,'مراجعة');
INSERT INTO curriculum(grade,subject,week,lesson) VALUES (6,'علوم',17,'مراجعة عامة');
