name = "nawatej-abudawood"
main = "_worker.js"
compatibility_date = "2026-09-14"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "nawatej2"
database_id = "PUT_DATABASE_ID_HERE"
